/**
 * Reason for throwing [[InvalidData]] error.
 * @category Errors
 */
export enum InvalidDataReason {
    GET_PUB_KEY_PATH_IS_NOT_ARRAY = "ext pub key path is not an array",
    INVALID_CHAIN_ID = "invalid chain id",
    INVALID_PATH = "invalid path",
    CONTEXT_FREE_ACTIONS_NOT_SUPPORTED = "context free actions not supported",
    MULTIPLE_ACTIONS_NOT_SUPPORTED = "multiple actions not supported",
    ACTION_NOT_SUPPORTED = "action not suported",
    INVALID_ACCOUNT = "invalid account",
    INVALID_NAME = "invalid name",
    INVALID_AMOUNT = "invalid amount",
    INVALID_MAX_FEE = "invalid max fee",
    INVALID_EXPIRATION = "invalid expiration",
    INVALID_REF_BLOCK_NUM = "invalid ref block num",
    INVALID_REF_BLOCK_PREFIX = "invalid ref block prefix",
    MULTIPLE_AUTHORIZATION_NOT_SUPPORTED = "multiple authorization not supported",
    INVALID_ACTION_AUTHORIZATION = "invalid action authorization",
    INVALID_PAYEE_PUBKEY = "invalid payee pubkey",
    INVALID_TPID = "invalid tpid",
    INVALID_ACTOR = "invalid actor",
    INVALID_PERMISSION = "invalid permission",
    ACTION_DATA_TOO_LONG = "action data too long",
    UNEXPECTED_ERROR = "Unexpected error",
    INVALID_PAYER_FIO_ADDRESS =  "invalid payer fio address",
    INVALID_PAYEE_FIO_ADDRESS =  "invalid payer fio address",
    INVALID_FIO_ADDRESS =  "invalid fio address",
    INVALID_PAYER_PUBLIC_ADDRESS =  "invalid payer public address",
    INVALID_PAYEE_PUBLIC_ADDRESS =  "invalid payer public address",
    INVALID_PUBLIC_ADDRESS =  "invalid public address",
    INVALID_CHAIN_CODE = "invalid chain code",
    INVALID_TOKEN_CODE = "invalid token code",
    INVALID_PUBLIC_KEY = "invalid public key",
    INVALID_MEMO = "invalid memo",
    INVALID_HASH = "invalid hash",
    INVALID_OFFLINE_URL = "invalid offline url",
    INVALID_FIO_REQUEST_ID = "invalid fio request id",
    INVALID_STATUS = "invalid status",
    INVALID_OBT_ID = "invalid opt id",
    INVALID_MESSAGE = "invalid message",
    INVALID_CONTEXT = "invalid context",
    INCORRECT_NUMBER_OF_PUBLIC_ADDRESSES = "incorrect number of public addresses",
    INCORRECT_NUMBER_OF_NFTS = "incorrect number of nfts",
    INVALID_BUNDLE_SETS = "invalid bundle sets",
    INVALID_IS_PUBLIC = "ivalid is public",
    INCORRECT_NUMBER_OF_PRODUCERS = "incorrect number of producers",
    INVALID_PRODUCER = "invalid producer",
    INVALID_PROXY = "invalid proxy",
}
